version: '3'
services:
  app:
    image: php:8.3.4-apache
    command: ["bash", "-c", "docker-php-ext-install pdo_mysql && apache2-foreground"]
    volumes:
      #  volumesでローカルファイルをDockerコンテナ内に結び付ける。
      # ローカルのsrc以下のファイルがDockerコンテナ内の/var/www/html内にマウント（≒コピー）される。
      # ローカルのsrcにファイルを置くと、Dockerコンテナ内の指定しているディレクトリにコピーされ、逆もまた然り。
      - ./src:/var/www/html
    ports:
      # コンテナポート - ホストポート
      - "80:80"
    depends_on:
      # dbコンテナ -> appコンテナの順で起動
      - db
    container_name: php

  db:
    image: mysql:5.7
    volumes:
      # MySQLのデータをローカルにコピーしている。
      # そうしないとコンテナを消してしまうとデータが吹き飛ぶため。
      - ./docker/mysql/data:/var/lib/mysql
       # コンテナ作成時に実行されるsqlファイルを格納するパス
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      # コンテナポート - ホストポート
      - "3306:3306"
    environment:
      # DBの初期設定
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=sampledb
      - MYSQL_USER=sampleuser
      - MYSQL_PASSWORD=samplepass
    container_name: mysql